### ISSUE TITLE
Crash on install. Could not import module memoization

### ISSUE THREAD

**Issue by jpmorr** [brpaz/ulauncher-lastpass#1]
Doesn't seem to work for me. Suggests ````pip3 install memoization --user````, but this is already installed. Removed and re-added ans still the same.

**Comment by schneik80** [comment]
Fails to load. I see the same errors as @jpmorr

**Comment by schneik80** [comment]
after restarting and installing lastpass CLI i was able to get the extension to work.
'sudo apt install lastpass-cli'
Then login through terminal 'lpass login username'

**Comment by brpaz** [comment]
Yes. this extension uses lastpass-cli under the hood.
